# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azurectx < Formula
  desc "Easily switch between Azure subscriptions"
  homepage "https://github.com/drewstinnett/azurectx-go"
  version "0.0.1"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/azurectx-go/releases/download/v0.0.1/azurectx-0.0.1_macOS_amd64.tar.gz"
      sha256 "091095486677b9445ba7c44b5edbf8022bf3b954d914c48cb022c41e3c0cf991"

      def install
        bin.install "azurectx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drewstinnett/azurectx-go/releases/download/v0.0.1/azurectx-0.0.1_macOS_arm64.tar.gz"
      sha256 "1f67cc7e11d56b3cd24ce7b56feacac5ae6f55b0d54bcea0804e0abf622e48a6"

      def install
        bin.install "azurectx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewstinnett/azurectx-go/releases/download/v0.0.1/azurectx-0.0.1_linux_arm64.tar.gz"
      sha256 "c5fa49adfb44cdfb0b671761b49f055a64b8020a6a677c2b1d575fd5bc8d9f44"

      def install
        bin.install "azurectx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/azurectx-go/releases/download/v0.0.1/azurectx-0.0.1_linux_amd64.tar.gz"
      sha256 "a9f23cf05b2165bde7c0a36388596872ea4a948139b7d561e796f0311a453536"

      def install
        bin.install "azurectx"
      end
    end
  end
end
