# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azurectx < Formula
  desc "Easily switch between Azure subscriptions"
  homepage "https://github.com/drewstinnett/azurectx-go"
  version "0.1.0"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/drewstinnett/azurectx-go/releases/download/v0.1.0/azurectx-0.1.0_macOS_arm64.tar.gz"
      sha256 "56d33b9fba9d8a44da721d721b8de4b83f51d653e990b2bf1563cb70ea5c9bb9"

      def install
        bin.install "azurectx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/azurectx-go/releases/download/v0.1.0/azurectx-0.1.0_macOS_amd64.tar.gz"
      sha256 "62296a2235a18158e523836dc0a4d953cb4b8e0faee90b9370b6f65734a82f45"

      def install
        bin.install "azurectx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/azurectx-go/releases/download/v0.1.0/azurectx-0.1.0_linux_amd64.tar.gz"
      sha256 "59540a64d7a45c8b973b32b36afff273b7b5865936bb6787c20110d79241740b"

      def install
        bin.install "azurectx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewstinnett/azurectx-go/releases/download/v0.1.0/azurectx-0.1.0_linux_arm64.tar.gz"
      sha256 "63aa3c8c9d60f6defad5cba8c57ba50759081a739ab987ced45dd65ceaf80dc7"

      def install
        bin.install "azurectx"
      end
    end
  end
end
