# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azurectx < Formula
  desc "Easily switch between Azure subscriptions"
  homepage "https://github.com/drewstinnett/azurectx-go"
  version "0.2.0"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/drewstinnett/azurectx-go/releases/download/v0.2.0/azurectx-0.2.0_macOS_arm64.tar.gz"
      sha256 "0b1c0652cd5a2bc2dce56db806e99235b9d93e2b2e8135e09d4f63a1ecd568c1"

      def install
        bin.install "azurectx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/azurectx-go/releases/download/v0.2.0/azurectx-0.2.0_macOS_amd64.tar.gz"
      sha256 "aa6e45e1d5619d879a831060972ee754ffd6b188c1568c5f88ac51283a047161"

      def install
        bin.install "azurectx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/azurectx-go/releases/download/v0.2.0/azurectx-0.2.0_linux_amd64.tar.gz"
      sha256 "bc4c8e91ba65d627bb802f2ba8beeee0d32445001867cb1ee7150c725fbbc3fe"

      def install
        bin.install "azurectx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewstinnett/azurectx-go/releases/download/v0.2.0/azurectx-0.2.0_linux_arm64.tar.gz"
      sha256 "73673e4f65f645896e845a6a004674ee969f4d65c71b02d3c1502d469f50a613"

      def install
        bin.install "azurectx"
      end
    end
  end
end
