# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flipip < Formula
  desc "Get reverse IP pointers on the cli"
  homepage "https://github.com/drewstinnett/flipip"
  version "0.1.0"
  license "APACHE-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/drewstinnett/flipip/releases/download/v0.1.0/flipip-0.1.0_macOS_arm64.tar.gz"
      sha256 "52fd0bbdb2c07180cc6170f8629246d3361d068dd9c1cfcf759bc32c1079fd84"
    end
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/flipip/releases/download/v0.1.0/flipip-0.1.0_macOS_amd64.tar.gz"
      sha256 "5d1ef288c57ab4eb352b91db943172e64685a75dec776fef9e275a50c05acf53"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewstinnett/flipip/releases/download/v0.1.0/flipip-0.1.0_linux_arm64.tar.gz"
      sha256 "937e13d463f8dbdc422c7d36191a9bcd01cc808f318b321a4c899d5f358cdd54"
    end
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/flipip/releases/download/v0.1.0/flipip-0.1.0_linux_amd64.tar.gz"
      sha256 "679e1509559093758038bcc95cd93dbb43e1cbfc59c254fe0f1a3650675fdb9f"
    end
  end

  def install
    bin.install "flipip"
  end
end
