# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flipip < Formula
  desc "Get reverse IP pointers on the cli"
  homepage "https://github.com/drewstinnett/flipip"
  version "0.1.1"
  license "APACHE-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/drewstinnett/flipip/releases/download/v0.1.1/flipip-0.1.1_macOS_arm64.tar.gz"
      sha256 "8171c4fa50ea8e9298e6678c4c17b8008e8627eecdfd959935b0d7560663f484"

      def install
        bin.install "flipip"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/flipip/releases/download/v0.1.1/flipip-0.1.1_macOS_amd64.tar.gz"
      sha256 "fe3cd5607b223ee5f814b2ca135879291d0072c3a206d16aacb77633259070a2"

      def install
        bin.install "flipip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/flipip/releases/download/v0.1.1/flipip-0.1.1_linux_amd64.tar.gz"
      sha256 "81f778a1c34d5f99f583865fd489f37d2469b41f0c3b0709c6eb247d8844fe3d"

      def install
        bin.install "flipip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewstinnett/flipip/releases/download/v0.1.1/flipip-0.1.1_linux_arm64.tar.gz"
      sha256 "dcfae802b5f668049d23941e21c0d35eb53c50e1dce3a64d5cd2d664248ede13"

      def install
        bin.install "flipip"
      end
    end
  end
end
