# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Labdoc < Formula
  desc "Generate README from a template, with some handy GitLab data"
  homepage "https://github.com/drewstinnett/labdoc"
  version "0.0.4"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/labdoc/releases/download/v0.0.4/labdoc-0.0.4_macOS_amd64.tar.gz"
      sha256 "d0f5da4342c1f6ab6068dbf3ab53b50c5a32f1d244fec655855ea54e6a6a7c58"

      def install
        bin.install "labdoc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drewstinnett/labdoc/releases/download/v0.0.4/labdoc-0.0.4_macOS_arm64.tar.gz"
      sha256 "79c6c69d078c9992a2e2fb8a89470b47b101abc6f490b070ee1bd1b6cbcfaf41"

      def install
        bin.install "labdoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewstinnett/labdoc/releases/download/v0.0.4/labdoc-0.0.4_linux_arm64.tar.gz"
      sha256 "1785f0323c9e897354f0e65eb5661282be9e217dd3616d63496cb56b06b2979f"

      def install
        bin.install "labdoc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/labdoc/releases/download/v0.0.4/labdoc-0.0.4_linux_amd64.tar.gz"
      sha256 "4345cd5f846d7e55fbb82de941ef3b7d17a8962285951957ae3d0ad1f9f98efd"

      def install
        bin.install "labdoc"
      end
    end
  end
end
