# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Letseat < Formula
  desc "Figure out where to go for dinner!"
  homepage "https://github.com/drewstinnett/letseat"
  version "0.0.5"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/drewstinnett/letseat/releases/download/v0.0.5/letseat-0.0.5_darwin_arm64.tar.gz"
      sha256 "69dbbb4fff07d144acbe364e37d4f2ff5cfa7fb09d336ba20e1046fe06a44aae"

      def install
        bin.install "letseat"
        bash_completion.install "completions/letseat.bash" => "letseat"
        zsh_completion.install "completions/letseat.zsh" => "_letseat"
        fish_completion.install "completions/letseat.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/letseat/releases/download/v0.0.5/letseat-0.0.5_darwin_amd64.tar.gz"
      sha256 "0d6c388c5e89fe458800cc470dd144773a52958602cf86a4b3c789430232b859"

      def install
        bin.install "letseat"
        bash_completion.install "completions/letseat.bash" => "letseat"
        zsh_completion.install "completions/letseat.zsh" => "_letseat"
        fish_completion.install "completions/letseat.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewstinnett/letseat/releases/download/v0.0.5/letseat-0.0.5_linux_arm64.tar.gz"
      sha256 "e6a552e82bc4626c7aad19682b17b1b2607c1181aafca559288c57957f55ea47"

      def install
        bin.install "letseat"
        bash_completion.install "completions/letseat.bash" => "letseat"
        zsh_completion.install "completions/letseat.zsh" => "_letseat"
        fish_completion.install "completions/letseat.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/letseat/releases/download/v0.0.5/letseat-0.0.5_linux_amd64.tar.gz"
      sha256 "9ad8e13b1a67da3eeb5445982a6c723cd5f63445ee62092d64ab6cc4deee2175"

      def install
        bin.install "letseat"
        bash_completion.install "completions/letseat.bash" => "letseat"
        zsh_completion.install "completions/letseat.zsh" => "_letseat"
        fish_completion.install "completions/letseat.fish"
      end
    end
  end

  def caveats
    <<~EOS
      Add the following in your ~/.zshrc or ~/.profile for faster typin':

        alias tp="#{opt_bin}/letseat"
    EOS
  end
end
