# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Letterboxdctl < Formula
  desc "Letterboxd CLI Client"
  homepage "https://github.com/drewstinnett/letterboxdctl"
  version "0.1.4"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/drewstinnett/letterboxdctl/releases/download/v0.1.4/letterboxdctl-0.1.4_macOS_arm64.tar.gz"
      sha256 "90c76152443dba1fd2931b356b60f0633710b499ba95ff484d1cf7478a6ba2c6"

      def install
        bin.install "letterboxdctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/letterboxdctl/releases/download/v0.1.4/letterboxdctl-0.1.4_macOS_amd64.tar.gz"
      sha256 "a024df8795993fa88845f00033e5ae9a3f01d4ebb0a31637c5a4b7fa3ed7f14e"

      def install
        bin.install "letterboxdctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewstinnett/letterboxdctl/releases/download/v0.1.4/letterboxdctl-0.1.4_linux_arm64.tar.gz"
      sha256 "fe913d6725f8ab5aefc649554e41010eedaac84a3dde325a208a42953ca0aae1"

      def install
        bin.install "letterboxdctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/letterboxdctl/releases/download/v0.1.4/letterboxdctl-0.1.4_linux_amd64.tar.gz"
      sha256 "e0030a3c446e4ea3b7a0e7d423ded0fe7c734173049198732ac64974540ce8a3"

      def install
        bin.install "letterboxdctl"
      end
    end
  end
end
