# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Letterboxdctl < Formula
  desc "Letterboxd CLI Client"
  homepage "https://github.com/drewstinnett/letterboxdctl"
  version "0.1.3"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/letterboxdctl/releases/download/v0.1.3/letterboxdctl-0.1.3_macOS_amd64.tar.gz"
      sha256 "4ee544dcd83b5030781803d4530195f8f290e85cb7d179dc82e14cf6a36de4b5"

      def install
        bin.install "letterboxdctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drewstinnett/letterboxdctl/releases/download/v0.1.3/letterboxdctl-0.1.3_macOS_arm64.tar.gz"
      sha256 "88334f79409c51129973c1b1ddd9743c7d220349c136f8f5dd5085ba945f30c8"

      def install
        bin.install "letterboxdctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/letterboxdctl/releases/download/v0.1.3/letterboxdctl-0.1.3_linux_amd64.tar.gz"
      sha256 "93ebac735c9fb82281ba88cc900db9f0fcbe8e178173797695e9fa06f0b2bb25"

      def install
        bin.install "letterboxdctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewstinnett/letterboxdctl/releases/download/v0.1.3/letterboxdctl-0.1.3_linux_arm64.tar.gz"
      sha256 "feada0894f18b24340f00cb7652e973456c47e710cb0f92124d57345c3a4b095"

      def install
        bin.install "letterboxdctl"
      end
    end
  end
end
