# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Letterboxdctl < Formula
  desc "Letterboxd CLI Client"
  homepage "https://github.com/drewstinnett/letterboxdctl"
  version "0.1.5"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/drewstinnett/letterboxdctl/releases/download/v0.1.5/letterboxdctl-0.1.5_macOS_arm64.tar.gz"
      sha256 "3c57e5dfe02ef1baa63329f81205f554d5e676d38f401107b245b205af5cec09"

      def install
        bin.install "letterboxdctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/letterboxdctl/releases/download/v0.1.5/letterboxdctl-0.1.5_macOS_amd64.tar.gz"
      sha256 "f7f274db811e1289d3a6971151418b86d97dca0c2d5db630c4bf62569f6c730b"

      def install
        bin.install "letterboxdctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewstinnett/letterboxdctl/releases/download/v0.1.5/letterboxdctl-0.1.5_linux_arm64.tar.gz"
      sha256 "09c6aa861e04cf7a987aef8290a13009ed8de7364bc82a1fb66ebf87e78508d2"

      def install
        bin.install "letterboxdctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/letterboxdctl/releases/download/v0.1.5/letterboxdctl-0.1.5_linux_amd64.tar.gz"
      sha256 "a93b5f19d338d3b1a98f762e550e9db4c33f879c165050ed2b87bbbb7b9aa208"

      def install
        bin.install "letterboxdctl"
      end
    end
  end
end
