# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sourceseedy < Formula
  desc "Easily switch between source directories"
  homepage "https://github.com/drewstinnett/sourceseedy"
  version "0.2.4"
  license "BSD-2-Clause"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/drewstinnett/sourceseedy/releases/download/v0.2.4/sourceseedy-0.2.4_macOS_arm64.tar.gz"
      sha256 "2aa17b7dab4b389e4f309179a43c45e541fe5528ab41db1cff2c2fa2174a99b4"
    end
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/sourceseedy/releases/download/v0.2.4/sourceseedy-0.2.4_macOS_amd64.tar.gz"
      sha256 "c50cb90b90a45ecbad43a7afdde11c724aff7c985b9878899f1c1b0edd577ebe"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/sourceseedy/releases/download/v0.2.4/sourceseedy-0.2.4_linux_amd64.tar.gz"
      sha256 "138df6e55e08cc0a7552fb839e2f8097aec17359c8ef0abed9d1944574f41a90"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewstinnett/sourceseedy/releases/download/v0.2.4/sourceseedy-0.2.4_linux_arm64.tar.gz"
      sha256 "106c5f349d37fb3fbdb89bd01fc1f10140891f4b1e35fa6cc38a89840bcc1e8e"
    end
  end

  def install
    bin.install "sourceseedy"
  end

  def caveats; <<~EOS
    Add the following in your ~/.zshrc or ~/.profile for faster typin':

      alias scd="#{opt_bin}/sourceseedy"
  EOS
  end
end
