# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sourceseedy < Formula
  desc "Easily switch between source directories"
  homepage "https://github.com/drewstinnett/sourceseedy"
  version "0.0.2"
  license "BSD-2-Clause"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/sourceseedy/releases/download/v0.0.2/sourceseedy-0.0.2_macOS_amd64.tar.gz"
      sha256 "d38ad7fe90343ff792a442852327330b6714ffa56c589bf623d4a64be2a59a7b"
    end
    if Hardware::CPU.arm?
      url "https://github.com/drewstinnett/sourceseedy/releases/download/v0.0.2/sourceseedy-0.0.2_macOS_arm64.tar.gz"
      sha256 "10c4072b8b46ccaeba5848b968838c793cdf2bb9349e53f866491ee06513e51c"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/sourceseedy/releases/download/v0.0.2/sourceseedy-0.0.2_linux_amd64.tar.gz"
      sha256 "730925f50bce78b2098472ac65d4c8ffc23ec88da6aad3167a266c3bda381327"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewstinnett/sourceseedy/releases/download/v0.0.2/sourceseedy-0.0.2_linux_arm64.tar.gz"
      sha256 "0834f4d7b0e25ca5a396a60c5df657d58b4e1d7a366ba8557b436939cd3e1541"
    end
  end

  def install
    bin.install "sourceseedy"
  end

  def caveats; <<~EOS
    Add the following in your ~/.zshrc or ~/.profile for faster typin':

      alias scd="#{opt_bin}/sourceseedy"
  EOS
  end
end
