# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trufflehog < Formula
  desc "Find credentials all over the place"
  homepage "https://github.com/trufflesecurity/trufflehog"
  version "3.0.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/drewstinnett/trufflehog/releases/download/v3.0.8/trufflehog_3.0.8_darwin_arm64.tar.gz"
      sha256 "f2c5ea265b8502dfc6266053bd62b7f6da3cad1e26eeb7d4808364b188c20956"

      def install
        bin.install "trufflehog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/trufflehog/releases/download/v3.0.8/trufflehog_3.0.8_darwin_amd64.tar.gz"
      sha256 "6c3fde6286fe81882a4564adcd561e74f19e7ca5b39cd7847e5bb545a8bd4af0"

      def install
        bin.install "trufflehog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewstinnett/trufflehog/releases/download/v3.0.8/trufflehog_3.0.8_linux_arm64.tar.gz"
      sha256 "d487dfde38709c41e427908f322b059b6ba27365d5992e51af2d933ab06759c3"

      def install
        bin.install "trufflehog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/trufflehog/releases/download/v3.0.8/trufflehog_3.0.8_linux_amd64.tar.gz"
      sha256 "4a9d4965ce05fbe3fda26c8df610be0430cfaa5eec6db20a1d0c40c439199c42"

      def install
        bin.install "trufflehog"
      end
    end
  end
end
