# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaultx < Formula
  desc "Generate README from a template, with some handy GitLab data"
  homepage "https://github.com/drewstinnett/vaultx"
  version "0.1.0"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/vaultx/releases/download/v0.1.0/vaultx-0.1.0_macOS_amd64.tar.gz"
      sha256 "622967b281156ae66fee15d1076d66c71cfea20ddf92f7654b39a90560428b07"

      def install
        bin.install "vaultx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drewstinnett/vaultx/releases/download/v0.1.0/vaultx-0.1.0_macOS_arm64.tar.gz"
      sha256 "dc4ca4ad0a3c3e1ce6497859728ea3c15137bfad328f4f7869f05bbd9f87ce0b"

      def install
        bin.install "vaultx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewstinnett/vaultx/releases/download/v0.1.0/vaultx-0.1.0_linux_arm64.tar.gz"
      sha256 "ee7b35916116865d82b1ee66cc47f23b570a22ffa39e3f28fe6eccb081e854c7"

      def install
        bin.install "vaultx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/vaultx/releases/download/v0.1.0/vaultx-0.1.0_linux_amd64.tar.gz"
      sha256 "ab714f769c5a268d0532c0103b51415d88b0fcad3ac29a973b6a9b404e47a177"

      def install
        bin.install "vaultx"
      end
    end
  end
end
