# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaultx < Formula
  desc "Generate README from a template, with some handy GitLab data"
  homepage "https://github.com/drewstinnett/vaultx"
  version "0.2.1"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/vaultx/releases/download/v0.2.1/vaultx-0.2.1_macOS_amd64.tar.gz"
      sha256 "d33d94bf9fd203ef2bdd5cd896f2526e898772a9d8600dcf54696b4b74b60701"

      def install
        bin.install "vaultx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drewstinnett/vaultx/releases/download/v0.2.1/vaultx-0.2.1_macOS_arm64.tar.gz"
      sha256 "d263db67622990d0bef10a5e352581d8821d9b868fb9a865981bbac85301159f"

      def install
        bin.install "vaultx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/drewstinnett/vaultx/releases/download/v0.2.1/vaultx-0.2.1_linux_amd64.tar.gz"
      sha256 "b4b229b156a8cb402fdacb7fefe8d9b6b358acb45713983979508ea66eb7bd23"

      def install
        bin.install "vaultx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewstinnett/vaultx/releases/download/v0.2.1/vaultx-0.2.1_linux_arm64.tar.gz"
      sha256 "6db8fbd21317613bb22bbc6e64093f259edce5b1b97eb698208310237796d954"

      def install
        bin.install "vaultx"
      end
    end
  end
end
